# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PandoraSettings.ui'
#
# Created: Mon Aug  3 19:57:00 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlg_PandoraSettings(object):
    def setupUi(self, dlg_PandoraSettings):
        dlg_PandoraSettings.setObjectName("dlg_PandoraSettings")
        dlg_PandoraSettings.resize(814, 631)
        self.verticalLayout = QtGui.QVBoxLayout(dlg_PandoraSettings)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(dlg_PandoraSettings)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 812, 629))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tw_settings = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tw_settings.setObjectName("tw_settings")
        self.tab_general = QtGui.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_general)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chb_checkForUpdates = QtGui.QCheckBox(self.tab_general)
        self.chb_checkForUpdates.setChecked(True)
        self.chb_checkForUpdates.setObjectName("chb_checkForUpdates")
        self.verticalLayout_4.addWidget(self.chb_checkForUpdates)
        self.chb_pandoraTrayStartup = QtGui.QCheckBox(self.tab_general)
        self.chb_pandoraTrayStartup.setChecked(True)
        self.chb_pandoraTrayStartup.setObjectName("chb_pandoraTrayStartup")
        self.verticalLayout_4.addWidget(self.chb_pandoraTrayStartup)
        self.chb_localMode = QtGui.QCheckBox(self.tab_general)
        self.chb_localMode.setChecked(True)
        self.chb_localMode.setObjectName("chb_localMode")
        self.verticalLayout_4.addWidget(self.chb_localMode)
        self.chb_errorReports = QtGui.QCheckBox(self.tab_general)
        self.chb_errorReports.setChecked(True)
        self.chb_errorReports.setObjectName("chb_errorReports")
        self.verticalLayout_4.addWidget(self.chb_errorReports)
        spacerItem = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.w_rootPath = QtGui.QWidget(self.tab_general)
        self.w_rootPath.setObjectName("w_rootPath")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.w_rootPath)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.l_rootPath = QtGui.QLabel(self.w_rootPath)
        self.l_rootPath.setObjectName("l_rootPath")
        self.verticalLayout_10.addWidget(self.l_rootPath)
        self.widget_20 = QtGui.QWidget(self.w_rootPath)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.widget_20)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.e_rootPath = QtGui.QLineEdit(self.widget_20)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_rootPath.setFont(font)
        self.e_rootPath.setObjectName("e_rootPath")
        self.horizontalLayout_19.addWidget(self.e_rootPath)
        self.b_browseRoot = QtGui.QPushButton(self.widget_20)
        self.b_browseRoot.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseRoot.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseRoot.setFont(font)
        self.b_browseRoot.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseRoot.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseRoot.setObjectName("b_browseRoot")
        self.horizontalLayout_19.addWidget(self.b_browseRoot)
        self.verticalLayout_10.addWidget(self.widget_20)
        self.verticalLayout_4.addWidget(self.w_rootPath)
        self.w_rootPath_2 = QtGui.QWidget(self.tab_general)
        self.w_rootPath_2.setObjectName("w_rootPath_2")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.w_rootPath_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.l_repositoryPath = QtGui.QLabel(self.w_rootPath_2)
        self.l_repositoryPath.setObjectName("l_repositoryPath")
        self.verticalLayout_11.addWidget(self.l_repositoryPath)
        self.widget_22 = QtGui.QWidget(self.w_rootPath_2)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.widget_22)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.e_repositoryPath = QtGui.QLineEdit(self.widget_22)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_repositoryPath.setFont(font)
        self.e_repositoryPath.setObjectName("e_repositoryPath")
        self.horizontalLayout_21.addWidget(self.e_repositoryPath)
        self.b_browseRepository = QtGui.QPushButton(self.widget_22)
        self.b_browseRepository.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseRepository.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseRepository.setFont(font)
        self.b_browseRepository.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseRepository.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseRepository.setObjectName("b_browseRepository")
        self.horizontalLayout_21.addWidget(self.b_browseRepository)
        self.verticalLayout_11.addWidget(self.widget_22)
        self.verticalLayout_4.addWidget(self.w_rootPath_2)
        self.widget_3 = QtGui.QWidget(self.tab_general)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_updatePandora = QtGui.QPushButton(self.widget_3)
        self.b_updatePandora.setObjectName("b_updatePandora")
        self.horizontalLayout_4.addWidget(self.b_updatePandora)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.widget_3)
        spacerItem2 = QtGui.QSpacerItem(20, 149, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tw_settings.addTab(self.tab_general, "")
        self.tab_submissions = QtGui.QWidget()
        self.tab_submissions.setObjectName("tab_submissions")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_submissions)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.w_sumitterPath = QtGui.QWidget(self.tab_submissions)
        self.w_sumitterPath.setObjectName("w_sumitterPath")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.w_sumitterPath)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtGui.QLabel(self.w_sumitterPath)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.widget_4 = QtGui.QWidget(self.w_sumitterPath)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.e_submissionPath = QtGui.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_submissionPath.setFont(font)
        self.e_submissionPath.setObjectName("e_submissionPath")
        self.horizontalLayout_2.addWidget(self.e_submissionPath)
        self.b_browseSubmission = QtGui.QPushButton(self.widget_4)
        self.b_browseSubmission.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseSubmission.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseSubmission.setFont(font)
        self.b_browseSubmission.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseSubmission.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseSubmission.setObjectName("b_browseSubmission")
        self.horizontalLayout_2.addWidget(self.b_browseSubmission)
        self.verticalLayout_9.addWidget(self.widget_4)
        spacerItem3 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.w_sumitterPath)
        self.w_username = QtGui.QWidget(self.tab_submissions)
        self.w_username.setObjectName("w_username")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.w_username)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.l_username = QtGui.QLabel(self.w_username)
        self.l_username.setObjectName("l_username")
        self.horizontalLayout_8.addWidget(self.l_username)
        self.e_username = QtGui.QLineEdit(self.w_username)
        self.e_username.setObjectName("e_username")
        self.horizontalLayout_8.addWidget(self.e_username)
        self.verticalLayout_2.addWidget(self.w_username)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.tw_settings.addTab(self.tab_submissions, "")
        self.tab_slave = QtGui.QWidget()
        self.tab_slave.setObjectName("tab_slave")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.tab_slave)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gb_slave = QtGui.QGroupBox(self.tab_slave)
        self.gb_slave.setCheckable(True)
        self.gb_slave.setChecked(False)
        self.gb_slave.setObjectName("gb_slave")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.gb_slave)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.w_slaveRoot = QtGui.QWidget(self.gb_slave)
        self.w_slaveRoot.setObjectName("w_slaveRoot")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.w_slaveRoot)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtGui.QLabel(self.w_slaveRoot)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.widget_18 = QtGui.QWidget(self.w_slaveRoot)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.widget_18)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.e_slavePath = QtGui.QLineEdit(self.widget_18)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_slavePath.setFont(font)
        self.e_slavePath.setObjectName("e_slavePath")
        self.horizontalLayout_17.addWidget(self.e_slavePath)
        self.b_browseSlave = QtGui.QPushButton(self.widget_18)
        self.b_browseSlave.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseSlave.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseSlave.setFont(font)
        self.b_browseSlave.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseSlave.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseSlave.setObjectName("b_browseSlave")
        self.horizontalLayout_17.addWidget(self.b_browseSlave)
        self.verticalLayout_12.addWidget(self.widget_18)
        self.verticalLayout_18.addWidget(self.w_slaveRoot)
        self.chb_slaveStartup = QtGui.QCheckBox(self.gb_slave)
        self.chb_slaveStartup.setChecked(True)
        self.chb_slaveStartup.setObjectName("chb_slaveStartup")
        self.verticalLayout_18.addWidget(self.chb_slaveStartup)
        self.verticalLayout_19.addWidget(self.gb_slave)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem5)
        self.tw_settings.addTab(self.tab_slave, "")
        self.tab_coordinator = QtGui.QWidget()
        self.tab_coordinator.setObjectName("tab_coordinator")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_coordinator)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gb_coordinator = QtGui.QGroupBox(self.tab_coordinator)
        self.gb_coordinator.setCheckable(True)
        self.gb_coordinator.setChecked(False)
        self.gb_coordinator.setObjectName("gb_coordinator")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.gb_coordinator)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.w_coordinatorRoot = QtGui.QWidget(self.gb_coordinator)
        self.w_coordinatorRoot.setObjectName("w_coordinatorRoot")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.w_coordinatorRoot)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_19 = QtGui.QLabel(self.w_coordinatorRoot)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.widget_21 = QtGui.QWidget(self.w_coordinatorRoot)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widget_21)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.e_coordinatorRoot = QtGui.QLineEdit(self.widget_21)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_coordinatorRoot.setFont(font)
        self.e_coordinatorRoot.setObjectName("e_coordinatorRoot")
        self.horizontalLayout_20.addWidget(self.e_coordinatorRoot)
        self.b_browseCoordinatorRoot = QtGui.QPushButton(self.widget_21)
        self.b_browseCoordinatorRoot.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseCoordinatorRoot.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseCoordinatorRoot.setFont(font)
        self.b_browseCoordinatorRoot.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseCoordinatorRoot.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseCoordinatorRoot.setObjectName("b_browseCoordinatorRoot")
        self.horizontalLayout_20.addWidget(self.b_browseCoordinatorRoot)
        self.verticalLayout_13.addWidget(self.widget_21)
        self.verticalLayout_20.addWidget(self.w_coordinatorRoot)
        self.chb_coordinatorStartup = QtGui.QCheckBox(self.gb_coordinator)
        self.chb_coordinatorStartup.setChecked(True)
        self.chb_coordinatorStartup.setObjectName("chb_coordinatorStartup")
        self.verticalLayout_20.addWidget(self.chb_coordinatorStartup)
        self.w_farmcomputer = QtGui.QWidget(self.gb_coordinator)
        self.w_farmcomputer.setObjectName("w_farmcomputer")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.w_farmcomputer)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem6)
        self.tw_slaves = QtGui.QTabWidget(self.w_farmcomputer)
        self.tw_slaves.setObjectName("tw_slaves")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lw_slaves = QtGui.QListWidget(self.tab_4)
        self.lw_slaves.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_slaves.setObjectName("lw_slaves")
        self.horizontalLayout.addWidget(self.lw_slaves)
        self.widget = QtGui.QWidget(self.tab_4)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.b_addSlave = QtGui.QPushButton(self.widget)
        self.b_addSlave.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_addSlave.setObjectName("b_addSlave")
        self.verticalLayout_6.addWidget(self.b_addSlave)
        self.b_deleteSlave = QtGui.QPushButton(self.widget)
        self.b_deleteSlave.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_deleteSlave.setObjectName("b_deleteSlave")
        self.verticalLayout_6.addWidget(self.b_deleteSlave)
        self.b_refreshSlaves = QtGui.QPushButton(self.widget)
        self.b_refreshSlaves.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_refreshSlaves.setObjectName("b_refreshSlaves")
        self.verticalLayout_6.addWidget(self.b_refreshSlaves)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout.addWidget(self.widget)
        self.tw_slaves.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lw_workstations = QtGui.QListWidget(self.tab_5)
        self.lw_workstations.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_workstations.setObjectName("lw_workstations")
        self.horizontalLayout_3.addWidget(self.lw_workstations)
        self.widget_2 = QtGui.QWidget(self.tab_5)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.b_addWS = QtGui.QPushButton(self.widget_2)
        self.b_addWS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_addWS.setObjectName("b_addWS")
        self.verticalLayout_7.addWidget(self.b_addWS)
        self.b_deleteWS = QtGui.QPushButton(self.widget_2)
        self.b_deleteWS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_deleteWS.setObjectName("b_deleteWS")
        self.verticalLayout_7.addWidget(self.b_deleteWS)
        self.b_refreshWS = QtGui.QPushButton(self.widget_2)
        self.b_refreshWS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_refreshWS.setObjectName("b_refreshWS")
        self.verticalLayout_7.addWidget(self.b_refreshWS)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.tw_slaves.addTab(self.tab_5, "")
        self.verticalLayout_14.addWidget(self.tw_slaves)
        self.verticalLayout_20.addWidget(self.w_farmcomputer)
        self.verticalLayout_3.addWidget(self.gb_coordinator)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.tw_settings.addTab(self.tab_coordinator, "")
        self.tab_dccApps = QtGui.QWidget()
        self.tab_dccApps.setObjectName("tab_dccApps")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tab_dccApps)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_23 = QtGui.QWidget(self.tab_dccApps)
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.widget_23)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_15.addWidget(self.widget_23)
        self.tw_settings.addTab(self.tab_dccApps, "")
        self.verticalLayout_5.addWidget(self.tw_settings)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.buttonBox = QtGui.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_5.addWidget(self.buttonBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(dlg_PandoraSettings)
        self.tw_settings.setCurrentIndex(0)
        self.tw_slaves.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dlg_PandoraSettings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dlg_PandoraSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_PandoraSettings)

    def retranslateUi(self, dlg_PandoraSettings):
        dlg_PandoraSettings.setWindowTitle(QtGui.QApplication.translate("dlg_PandoraSettings", "Pandora Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_checkForUpdates.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Check for updates (once per week)", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_pandoraTrayStartup.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Start tray icon on Windows startup", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_localMode.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Local network mode", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_errorReports.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Send anonymous error reports", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rootPath.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Pandora Root (network location):", None, QtGui.QApplication.UnicodeUTF8))
        self.b_browseRoot.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.l_repositoryPath.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Local repository:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_browseRepository.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.b_updatePandora.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Update Pandora", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_general), QtGui.QApplication.translate("dlg_PandoraSettings", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Job submission path:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_browseSubmission.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.l_username.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_submissions), QtGui.QApplication.translate("dlg_PandoraSettings", "Submissions", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_slave.setTitle(QtGui.QApplication.translate("dlg_PandoraSettings", "Enable Pandora Renderslave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Slave Root:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_browseSlave.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_slaveStartup.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Start Pandora slave on Windows startup", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_slave), QtGui.QApplication.translate("dlg_PandoraSettings", "Slave", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_coordinator.setTitle(QtGui.QApplication.translate("dlg_PandoraSettings", "Enable Pandora Coordinator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Pandora Root:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_browseCoordinatorRoot.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.chb_coordinatorStartup.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Start Pandora Coordinator on Windows startup", None, QtGui.QApplication.UnicodeUTF8))
        self.b_addSlave.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.b_deleteSlave.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.b_refreshSlaves.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_slaves.setTabText(self.tw_slaves.indexOf(self.tab_4), QtGui.QApplication.translate("dlg_PandoraSettings", "Slaves", None, QtGui.QApplication.UnicodeUTF8))
        self.b_addWS.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.b_deleteWS.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.b_refreshWS.setText(QtGui.QApplication.translate("dlg_PandoraSettings", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_slaves.setTabText(self.tw_slaves.indexOf(self.tab_5), QtGui.QApplication.translate("dlg_PandoraSettings", "Submitters", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_coordinator), QtGui.QApplication.translate("dlg_PandoraSettings", "Coordinator", None, QtGui.QApplication.UnicodeUTF8))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_dccApps), QtGui.QApplication.translate("dlg_PandoraSettings", "DCC apps", None, QtGui.QApplication.UnicodeUTF8))

