# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PandoraSettings.ui'
#
# Created: Tue Jun 12 22:41:09 2018
#      by: pyside2-uic @pyside_tools_VERSION@ running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dlg_PandoraSettings(object):
    def setupUi(self, dlg_PandoraSettings):
        dlg_PandoraSettings.setObjectName("dlg_PandoraSettings")
        dlg_PandoraSettings.resize(676, 603)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlg_PandoraSettings)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(dlg_PandoraSettings)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 674, 601))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tw_settings = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tw_settings.setObjectName("tw_settings")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chb_pandoraTrayStartup = QtWidgets.QCheckBox(self.tab_3)
        self.chb_pandoraTrayStartup.setChecked(True)
        self.chb_pandoraTrayStartup.setObjectName("chb_pandoraTrayStartup")
        self.verticalLayout_4.addWidget(self.chb_pandoraTrayStartup)
        self.chb_localMode = QtWidgets.QCheckBox(self.tab_3)
        self.chb_localMode.setChecked(True)
        self.chb_localMode.setObjectName("chb_localMode")
        self.verticalLayout_4.addWidget(self.chb_localMode)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.w_rootPath = QtWidgets.QWidget(self.tab_3)
        self.w_rootPath.setObjectName("w_rootPath")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.w_rootPath)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.l_rootPath = QtWidgets.QLabel(self.w_rootPath)
        self.l_rootPath.setObjectName("l_rootPath")
        self.verticalLayout_10.addWidget(self.l_rootPath)
        self.widget_20 = QtWidgets.QWidget(self.w_rootPath)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.e_rootPath = QtWidgets.QLineEdit(self.widget_20)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_rootPath.setFont(font)
        self.e_rootPath.setObjectName("e_rootPath")
        self.horizontalLayout_19.addWidget(self.e_rootPath)
        self.b_browseRoot = QtWidgets.QPushButton(self.widget_20)
        self.b_browseRoot.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseRoot.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseRoot.setFont(font)
        self.b_browseRoot.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseRoot.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseRoot.setObjectName("b_browseRoot")
        self.horizontalLayout_19.addWidget(self.b_browseRoot)
        self.verticalLayout_10.addWidget(self.widget_20)
        self.verticalLayout_4.addWidget(self.w_rootPath)
        self.w_rootPath_2 = QtWidgets.QWidget(self.tab_3)
        self.w_rootPath_2.setObjectName("w_rootPath_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.w_rootPath_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.l_repositoryPath = QtWidgets.QLabel(self.w_rootPath_2)
        self.l_repositoryPath.setObjectName("l_repositoryPath")
        self.verticalLayout_11.addWidget(self.l_repositoryPath)
        self.widget_22 = QtWidgets.QWidget(self.w_rootPath_2)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.e_repositoryPath = QtWidgets.QLineEdit(self.widget_22)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_repositoryPath.setFont(font)
        self.e_repositoryPath.setObjectName("e_repositoryPath")
        self.horizontalLayout_21.addWidget(self.e_repositoryPath)
        self.b_browseRepository = QtWidgets.QPushButton(self.widget_22)
        self.b_browseRepository.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseRepository.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseRepository.setFont(font)
        self.b_browseRepository.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseRepository.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseRepository.setObjectName("b_browseRepository")
        self.horizontalLayout_21.addWidget(self.b_browseRepository)
        self.verticalLayout_11.addWidget(self.widget_22)
        self.verticalLayout_4.addWidget(self.w_rootPath_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 149, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tw_settings.addTab(self.tab_3, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabWidgetPage3)
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gb_submission = QtWidgets.QGroupBox(self.tabWidgetPage3)
        self.gb_submission.setCheckable(True)
        self.gb_submission.setChecked(False)
        self.gb_submission.setObjectName("gb_submission")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.gb_submission)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.w_sumitterPath = QtWidgets.QWidget(self.gb_submission)
        self.w_sumitterPath.setObjectName("w_sumitterPath")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.w_sumitterPath)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.w_sumitterPath)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.widget_4 = QtWidgets.QWidget(self.w_sumitterPath)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.e_submissionPath = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_submissionPath.setFont(font)
        self.e_submissionPath.setObjectName("e_submissionPath")
        self.horizontalLayout_2.addWidget(self.e_submissionPath)
        self.b_browseSubmission = QtWidgets.QPushButton(self.widget_4)
        self.b_browseSubmission.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseSubmission.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseSubmission.setFont(font)
        self.b_browseSubmission.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseSubmission.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseSubmission.setObjectName("b_browseSubmission")
        self.horizontalLayout_2.addWidget(self.b_browseSubmission)
        self.verticalLayout_9.addWidget(self.widget_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem2)
        self.verticalLayout_17.addWidget(self.w_sumitterPath)
        self.w_username = QtWidgets.QWidget(self.gb_submission)
        self.w_username.setObjectName("w_username")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.w_username)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.l_username = QtWidgets.QLabel(self.w_username)
        self.l_username.setObjectName("l_username")
        self.horizontalLayout_8.addWidget(self.l_username)
        self.e_username = QtWidgets.QLineEdit(self.w_username)
        self.e_username.setObjectName("e_username")
        self.horizontalLayout_8.addWidget(self.e_username)
        self.verticalLayout_17.addWidget(self.w_username)
        self.verticalLayout_2.addWidget(self.gb_submission)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tw_settings.addTab(self.tabWidgetPage3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gb_slave = QtWidgets.QGroupBox(self.tab_2)
        self.gb_slave.setCheckable(True)
        self.gb_slave.setChecked(False)
        self.gb_slave.setObjectName("gb_slave")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.gb_slave)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.w_slaveRoot = QtWidgets.QWidget(self.gb_slave)
        self.w_slaveRoot.setObjectName("w_slaveRoot")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.w_slaveRoot)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.w_slaveRoot)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.widget_18 = QtWidgets.QWidget(self.w_slaveRoot)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.e_slavePath = QtWidgets.QLineEdit(self.widget_18)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_slavePath.setFont(font)
        self.e_slavePath.setObjectName("e_slavePath")
        self.horizontalLayout_17.addWidget(self.e_slavePath)
        self.b_browseSlave = QtWidgets.QPushButton(self.widget_18)
        self.b_browseSlave.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseSlave.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseSlave.setFont(font)
        self.b_browseSlave.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseSlave.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseSlave.setObjectName("b_browseSlave")
        self.horizontalLayout_17.addWidget(self.b_browseSlave)
        self.verticalLayout_12.addWidget(self.widget_18)
        self.verticalLayout_18.addWidget(self.w_slaveRoot)
        self.chb_slaveStartup = QtWidgets.QCheckBox(self.gb_slave)
        self.chb_slaveStartup.setChecked(True)
        self.chb_slaveStartup.setObjectName("chb_slaveStartup")
        self.verticalLayout_18.addWidget(self.chb_slaveStartup)
        self.gb_dccOverride = QtWidgets.QGroupBox(self.gb_slave)
        self.gb_dccOverride.setObjectName("gb_dccOverride")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.gb_dccOverride)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.l_dccOverride = QtWidgets.QLabel(self.gb_dccOverride)
        self.l_dccOverride.setObjectName("l_dccOverride")
        self.verticalLayout_25.addWidget(self.l_dccOverride)
        self.widget_5 = QtWidgets.QWidget(self.gb_dccOverride)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.chb_overrideMax = QtWidgets.QCheckBox(self.widget_5)
        self.chb_overrideMax.setObjectName("chb_overrideMax")
        self.verticalLayout_8.addWidget(self.chb_overrideMax)
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.e_overrideMax = QtWidgets.QLineEdit(self.widget_3)
        self.e_overrideMax.setObjectName("e_overrideMax")
        self.horizontalLayout_4.addWidget(self.e_overrideMax)
        self.b_browseMaxOR = QtWidgets.QPushButton(self.widget_3)
        self.b_browseMaxOR.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseMaxOR.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseMaxOR.setFont(font)
        self.b_browseMaxOR.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseMaxOR.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseMaxOR.setObjectName("b_browseMaxOR")
        self.horizontalLayout_4.addWidget(self.b_browseMaxOR)
        self.verticalLayout_8.addWidget(self.widget_3)
        self.chb_overrideMaya = QtWidgets.QCheckBox(self.widget_5)
        self.chb_overrideMaya.setObjectName("chb_overrideMaya")
        self.verticalLayout_8.addWidget(self.chb_overrideMaya)
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.e_overrideMaya = QtWidgets.QLineEdit(self.widget_6)
        self.e_overrideMaya.setObjectName("e_overrideMaya")
        self.horizontalLayout_5.addWidget(self.e_overrideMaya)
        self.b_browseMayaOR = QtWidgets.QPushButton(self.widget_6)
        self.b_browseMayaOR.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseMayaOR.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseMayaOR.setFont(font)
        self.b_browseMayaOR.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseMayaOR.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseMayaOR.setObjectName("b_browseMayaOR")
        self.horizontalLayout_5.addWidget(self.b_browseMayaOR)
        self.verticalLayout_8.addWidget(self.widget_6)
        self.chb_overrideHoudini = QtWidgets.QCheckBox(self.widget_5)
        self.chb_overrideHoudini.setObjectName("chb_overrideHoudini")
        self.verticalLayout_8.addWidget(self.chb_overrideHoudini)
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.e_overrideHoudini = QtWidgets.QLineEdit(self.widget_7)
        self.e_overrideHoudini.setObjectName("e_overrideHoudini")
        self.horizontalLayout_6.addWidget(self.e_overrideHoudini)
        self.b_browseHoudiniOR = QtWidgets.QPushButton(self.widget_7)
        self.b_browseHoudiniOR.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseHoudiniOR.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseHoudiniOR.setFont(font)
        self.b_browseHoudiniOR.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseHoudiniOR.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseHoudiniOR.setObjectName("b_browseHoudiniOR")
        self.horizontalLayout_6.addWidget(self.b_browseHoudiniOR)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.chb_overrideBlender = QtWidgets.QCheckBox(self.widget_5)
        self.chb_overrideBlender.setObjectName("chb_overrideBlender")
        self.verticalLayout_8.addWidget(self.chb_overrideBlender)
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.e_overrideBlender = QtWidgets.QLineEdit(self.widget_8)
        self.e_overrideBlender.setObjectName("e_overrideBlender")
        self.horizontalLayout_7.addWidget(self.e_overrideBlender)
        self.b_browseBlenderOR = QtWidgets.QPushButton(self.widget_8)
        self.b_browseBlenderOR.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseBlenderOR.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseBlenderOR.setFont(font)
        self.b_browseBlenderOR.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseBlenderOR.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseBlenderOR.setObjectName("b_browseBlenderOR")
        self.horizontalLayout_7.addWidget(self.b_browseBlenderOR)
        self.verticalLayout_8.addWidget(self.widget_8)
        self.verticalLayout_25.addWidget(self.widget_5)
        self.verticalLayout_18.addWidget(self.gb_dccOverride)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem4)
        self.verticalLayout_19.addWidget(self.gb_slave)
        self.tw_settings.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gb_coordinator = QtWidgets.QGroupBox(self.tab)
        self.gb_coordinator.setCheckable(True)
        self.gb_coordinator.setChecked(False)
        self.gb_coordinator.setObjectName("gb_coordinator")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.gb_coordinator)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.w_coordinatorRoot = QtWidgets.QWidget(self.gb_coordinator)
        self.w_coordinatorRoot.setObjectName("w_coordinatorRoot")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.w_coordinatorRoot)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.w_coordinatorRoot)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.widget_21 = QtWidgets.QWidget(self.w_coordinatorRoot)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.e_coordinatorRoot = QtWidgets.QLineEdit(self.widget_21)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.e_coordinatorRoot.setFont(font)
        self.e_coordinatorRoot.setObjectName("e_coordinatorRoot")
        self.horizontalLayout_20.addWidget(self.e_coordinatorRoot)
        self.b_browseCoordinatorRoot = QtWidgets.QPushButton(self.widget_21)
        self.b_browseCoordinatorRoot.setMinimumSize(QtCore.QSize(50, 0))
        self.b_browseCoordinatorRoot.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.b_browseCoordinatorRoot.setFont(font)
        self.b_browseCoordinatorRoot.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_browseCoordinatorRoot.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_browseCoordinatorRoot.setObjectName("b_browseCoordinatorRoot")
        self.horizontalLayout_20.addWidget(self.b_browseCoordinatorRoot)
        self.verticalLayout_13.addWidget(self.widget_21)
        self.verticalLayout_20.addWidget(self.w_coordinatorRoot)
        self.chb_coordinatorStartup = QtWidgets.QCheckBox(self.gb_coordinator)
        self.chb_coordinatorStartup.setChecked(True)
        self.chb_coordinatorStartup.setObjectName("chb_coordinatorStartup")
        self.verticalLayout_20.addWidget(self.chb_coordinatorStartup)
        self.w_farmcomputer = QtWidgets.QWidget(self.gb_coordinator)
        self.w_farmcomputer.setObjectName("w_farmcomputer")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.w_farmcomputer)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem5)
        self.tw_slaves = QtWidgets.QTabWidget(self.w_farmcomputer)
        self.tw_slaves.setObjectName("tw_slaves")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lw_slaves = QtWidgets.QListWidget(self.tab_4)
        self.lw_slaves.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_slaves.setObjectName("lw_slaves")
        self.horizontalLayout.addWidget(self.lw_slaves)
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.b_addSlave = QtWidgets.QPushButton(self.widget)
        self.b_addSlave.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_addSlave.setObjectName("b_addSlave")
        self.verticalLayout_6.addWidget(self.b_addSlave)
        self.b_deleteSlave = QtWidgets.QPushButton(self.widget)
        self.b_deleteSlave.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_deleteSlave.setObjectName("b_deleteSlave")
        self.verticalLayout_6.addWidget(self.b_deleteSlave)
        self.b_refreshSlaves = QtWidgets.QPushButton(self.widget)
        self.b_refreshSlaves.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_refreshSlaves.setObjectName("b_refreshSlaves")
        self.verticalLayout_6.addWidget(self.b_refreshSlaves)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout.addWidget(self.widget)
        self.tw_slaves.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lw_workstations = QtWidgets.QListWidget(self.tab_5)
        self.lw_workstations.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lw_workstations.setObjectName("lw_workstations")
        self.horizontalLayout_3.addWidget(self.lw_workstations)
        self.widget_2 = QtWidgets.QWidget(self.tab_5)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.b_addWS = QtWidgets.QPushButton(self.widget_2)
        self.b_addWS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_addWS.setObjectName("b_addWS")
        self.verticalLayout_7.addWidget(self.b_addWS)
        self.b_deleteWS = QtWidgets.QPushButton(self.widget_2)
        self.b_deleteWS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_deleteWS.setObjectName("b_deleteWS")
        self.verticalLayout_7.addWidget(self.b_deleteWS)
        self.b_refreshWS = QtWidgets.QPushButton(self.widget_2)
        self.b_refreshWS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b_refreshWS.setObjectName("b_refreshWS")
        self.verticalLayout_7.addWidget(self.b_refreshWS)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.tw_slaves.addTab(self.tab_5, "")
        self.verticalLayout_14.addWidget(self.tw_slaves)
        self.verticalLayout_20.addWidget(self.w_farmcomputer)
        self.verticalLayout_3.addWidget(self.gb_coordinator)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.tw_settings.addTab(self.tab, "")
        self.verticalLayout_5.addWidget(self.tw_settings)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_5.addWidget(self.buttonBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(dlg_PandoraSettings)
        self.tw_settings.setCurrentIndex(0)
        self.tw_slaves.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), dlg_PandoraSettings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), dlg_PandoraSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_PandoraSettings)

    def retranslateUi(self, dlg_PandoraSettings):
        dlg_PandoraSettings.setWindowTitle(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Pandora Settings", None, -1))
        self.chb_pandoraTrayStartup.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Start tray icon on Windows startup", None, -1))
        self.chb_localMode.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Local network mode", None, -1))
        self.l_rootPath.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Pandora Root (network location):", None, -1))
        self.b_browseRoot.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "...", None, -1))
        self.l_repositoryPath.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Local repository:", None, -1))
        self.b_browseRepository.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "...", None, -1))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_3), QtWidgets.QApplication.translate("dlg_PandoraSettings", "General", None, -1))
        self.gb_submission.setTitle(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Enable Pandora job submissions", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Job submission path:", None, -1))
        self.b_browseSubmission.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "...", None, -1))
        self.l_username.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Username:", None, -1))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tabWidgetPage3), QtWidgets.QApplication.translate("dlg_PandoraSettings", "Submissions", None, -1))
        self.gb_slave.setTitle(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Enable Pandora Renderslave", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Slave Root:", None, -1))
        self.b_browseSlave.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "...", None, -1))
        self.chb_slaveStartup.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Start Pandora slave on Windows startup", None, -1))
        self.gb_dccOverride.setTitle(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Executable overrides", None, -1))
        self.l_dccOverride.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "By default Pandora tries to find the latest application version on your system for rendering the jobs.\n"
"The following settings let you override this behaviour by defining explicit applications for rendering jobs.", None, -1))
        self.chb_overrideMax.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "3ds Max (e.g. C:\\Program Files\\Autodesk\\3ds Max 2018\\3dsmaxcmd.exe)", None, -1))
        self.b_browseMaxOR.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "...", None, -1))
        self.chb_overrideMaya.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Maya (e.g. C:\\Program Files\\Autodesk\\Maya2018\\bin\\Render.exe)", None, -1))
        self.b_browseMayaOR.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "...", None, -1))
        self.chb_overrideHoudini.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Houdini (e.g. C:\\Program Files\\Side Effects Software\\Houdini 16.5.439\\bin\\hython.exe)", None, -1))
        self.b_browseHoudiniOR.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "...", None, -1))
        self.chb_overrideBlender.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Blender (e.g. C:\\Program Files\\Blender Foundation\\Blender\\blender.exe)", None, -1))
        self.b_browseBlenderOR.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "...", None, -1))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab_2), QtWidgets.QApplication.translate("dlg_PandoraSettings", "Slave", None, -1))
        self.gb_coordinator.setTitle(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Enable Pandora Coordinator", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Pandora Root:", None, -1))
        self.b_browseCoordinatorRoot.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "...", None, -1))
        self.chb_coordinatorStartup.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Start Pandora Coordinator on Windows startup", None, -1))
        self.b_addSlave.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Add", None, -1))
        self.b_deleteSlave.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Delete", None, -1))
        self.b_refreshSlaves.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Refresh", None, -1))
        self.tw_slaves.setTabText(self.tw_slaves.indexOf(self.tab_4), QtWidgets.QApplication.translate("dlg_PandoraSettings", "Slaves", None, -1))
        self.b_addWS.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Add", None, -1))
        self.b_deleteWS.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Delete", None, -1))
        self.b_refreshWS.setText(QtWidgets.QApplication.translate("dlg_PandoraSettings", "Refresh", None, -1))
        self.tw_slaves.setTabText(self.tw_slaves.indexOf(self.tab_5), QtWidgets.QApplication.translate("dlg_PandoraSettings", "Submitters", None, -1))
        self.tw_settings.setTabText(self.tw_settings.indexOf(self.tab), QtWidgets.QApplication.translate("dlg_PandoraSettings", "Coordinator", None, -1))

